CREATE USER 'dev'@'localhost' IDENTIFIED BY '123';
CREATE USER 'dev'@'%' IDENTIFIED BY '123';

GRANT ALL ON *.* TO 'dev'@'localhost';
GRANT ALL ON *.* TO 'dev'@'%';

FLUSH PRIVILEGES;

CREATE DATABASE Fidelidade;
USE Fidelidade;

CREATE TABLE USUARIO(
	ID_USUARIO INT,
    NOME VARCHAR(40) NOT NULL,
    CPF CHAR(11) NOT NULL,
    DATA_NASC DATE,
    EMAIL VARCHAR(40),
    TELEFONE CHAR(11),
    LOGIN VARCHAR(15) NOT NULL,
	SALDO DECIMAL (12,2) NOT NULL DEFAULT 0,
    constraint PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_CPF UNIQUE (CPF),
	CONSTRAINT UQ_LOGIN UNIQUE (LOGIN)
);

CREATE TABLE ENDERECO(
	ID_ENDERECO INT,
    ID_USUARIO INT,
	LOGRADOURO VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL,
    CEP CHAR(8) NOT NULL,
    BAIRRO VARCHAR(20) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    COMPLEMENTO VARCHAR(30),
    CONSTRAINT PK_ENDERECO PRIMARY KEY (ID_ENDERECO),
    CONSTRAINT FK_USUARIO_ENDERECO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE NOTA_FISCAL(
	ID_NOTA_FISCAL INT,
	ID_USUARIO INT,
	NOME_EMPRESA VARCHAR(40) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
	DATA_EMISSAO DATETIME NOT NULL,
	VALOR DECIMAL (12,2) NOT NULL,
	CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY (ID_NOTA_FISCAL),
	CONSTRAINT FK_USUARIO_NOTA_FISCAL FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PREMIO(
    ID_PREMIO INT,
    DESCRICAO VARCHAR(30) NOT NULL,
	PRECO DOUBLE(8,2) NOT NULL,
	QTD_DISPO INT DEFAULT 0,
	CONSTRAINT PK_PREMIO PRIMARY KEY (ID_PREMIO)
);

CREATE TABLE CREDITO(
	ID_CREDITO INT,
    VALOR DECIMAL(12,2) NOT NULL DEFAULT 0,
    DATA DATETIME NOT NULL,
    ID_USUARIO INT,
	ID_NOTA_FISCAL INT,
    CONSTRAINT PK_PONTUACAO PRIMARY KEY (ID_CREDITO),
    CONSTRAINT FK_USUARIO_CREDITO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_NOTA_FISCAL_CREDITO FOREIGN KEY (ID_NOTA_FISCAL) REFERENCES NOTA_FISCAL(ID_NOTA_FISCAL)
);

CREATE TABLE DEBITO (
	ID_DEBITO INT,
	VALOR DECIMAL (12,2) NOT NULL DEFAULT 0,
	DATA DATETIME NOT NULL,
	ID_USUARIO INT,
	ID_PREMIO INT,
	CONSTRAINT PK_DEBITO PRIMARY KEY (ID_DEBITO),
	CONSTRAINT FK_USUARIO_DEBITO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_PREMIO_DEBITO FOREIGN KEY (ID_PREMIO) REFERENCES PREMIO(ID_PREMIO)
);